### PR TITLE
Fixed giveaway example.

### PR DESCRIPTION
**Pull request by Sengolda**

### CODE REVIEW

**Review by TheGenocides — COMMENTED** [review]
hmm, if a user doesnt have followers it return 0.

**Comment by Sengolda** [comment]
> hmm, if a user doesnt have followers it return 0.

Ahhh I see, wouldn't it make more sense to return an empty list tho?

**Comment by TheGenocides** [comment]
> > hmm, if a user doesnt have followers it return 0.
> 
> Ahhh I see, wouldn't it make more sense to return an empty list tho?

Yep, coincidentally i am making it empty list right now.

**Review by TheGenocides — APPROVED** [review]
Approved

**Review by TheGenocides — CHANGES_REQUESTED** [review]
Wait, i just check it has breaking changes when i tried to merge, for this i will change is manually tomorrow, you may close this pr

**Pull request closed without merging**
